const sessions = [
  {
    subjectRef: 'CS',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kodagoda']
  },
  {
    subjectRef: 'IC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y3.S1.03',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kodagoda']
  },



];

export default sessions;
